feat: change pipeline

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -10,17 +10,20 @@ jobs:
       run:
         working-directory: ./frontend
 
-    permissions:
-      pages: write
-      id-token: write
+    # permissions:
+    #   pages: write
+    #   id-token: write
 
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+    # environment:
+    #   name: github-pages
+    #   url: ${{ steps.deployment.outputs.page_url }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+
+      - name: Set SSH key
+        run: set -eu && mkdir "$HOME/.ssh" && echo "${{ secrets.key }}" > "$HOME/.ssh/key" && chmod 600 "$HOME/.ssh/key"
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
@@ -36,27 +39,32 @@ jobs:
       - name: Generate project files
         run: npx nuxi generate
 
-      - name: Create deployment artifact
+      - name: Deploy frontend via SSH
         run: |
-          chmod -c -R +rX ".output/public/" | while read line; do
-            echo "::warning title=Invalid file permissions automatically fixed::$line"
-          done
-          tar \
-          --dereference --hard-dereference \
-          --directory ".output/public/" \
-          -cvf ".output/public/artifact.tar" \
-          --exclude=.git \
-          --exclude=.github \
-          .
+          cd .output/public
+          rsync -e "sshpass -p ${{ secrets.ROOT_PASSWORD }} ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@${{ secrets.SERVER_IP }}:/var/www/html
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v1
-        with:
-          name: github-pages
-          path: frontend/.output/public/artifact.tar
-          retention-days: '1'
-          if-no-files-found: error
+      # - name: Create deployment artifact
+      #   run: |
+      #     chmod -c -R +rX ".output/public/" | while read line; do
+      #       echo "::warning title=Invalid file permissions automatically fixed::$line"
+      #     done
+      #     tar \
+      #     --dereference --hard-dereference \
+      #     --directory ".output/public/" \
+      #     -cvf ".output/public/artifact.tar" \
+      #     --exclude=.git \
+      #     --exclude=.github \
+      #     .
 
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v2
+      # - name: Upload artifact
+      #   uses: actions/upload-artifact@v1
+      #   with:
+      #     name: github-pages
+      #     path: frontend/.output/public/artifact.tar
+      #     retention-days: '1'
+      #     if-no-files-found: error
+
+      # - name: Deploy to GitHub Pages
+      #   id: deployment
+      #   uses: actions/deploy-pages@v2
